#bytebites
server.port=${PORT:8080}

#db specific properties
spring.datasource.url=jdbc:mysql://localhost:3306/bytebites?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:manish}


#ORM s/w specific properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


stripe.api.key=${STRIPE_API_KEY:}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=msaini720415@gmial.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



