app = "bytebites-api"
primary_region = "sin"

[build]
  dockerfile = "backend-spring boot/Dockerfile"

[env]
  PORT = "5454"

[http_service]
  internal_port = 5454
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
